### ISSUE TITLE
Is this deprecated or still maintained?

### ISSUE THREAD

**Issue by mdonke** [adobe/aio-cli-plugin-aep#4]
Hello, 

I wonder if this will be maintained further by @BibhutiGaurav or other Adobe folks.

Issues I found (probably not complete)

- aep:mixins:update (the "U" in "CRUD") is missing
- x-sandbox-name must be provided in the header
- Mixins endpoint is deprecated, must be "fieldgroups"
- The used library [https://github.com/adobe/aio-cli-plugin-jwt-auth](https://github.com/adobe/aio-cli-plugin-jwt-auth) is deprecated

**Comment by eknee** [comment]
@mdonke, this is still being maintained and we have a small project underway to clean this up and get it working in a much better capacity.  I ask you bear with us on this as it will take some time.  In the meantime if there are things you would like to see please don't hesitate to open issues.
